### ISSUE TITLE
Ceiling light nicht RGB

### ISSUE THREAD

**Issue by quthla** [syssi/yeelight#1]
```
>>> bulb.get_properties()
{'power': 'on', 'bright': '61', 'ct': '2700', 'rgb': None, 'hue': None, 'sat': None, 'color_mode': '2', 'flowing': '0', 'delayoff': '0', 'music_on': None, 'name': None}
>>> bulb.bulb_type
<BulbType.Color: 1>

```

yeelight gibt BulbType.Color zurück, weil ct gesetzt ist, de facto ist das aber keine RGB-Lampe.
Kannst du dein Script anpassen und nicht pauschal SUPPORT_COLOR und SUPPORT_EFFECT setzen, wenn eigentlich nur SUPPORT_COLOR_TEMP sein sollte?

**Comment by quthla** [comment]
Und Lampe unterstützt nur bis runter zu 2700K, was etwa in der Mitte vom HA Slider ist. Wenn man von der Mitte nach rechts will, kommt:

```
May 24 16:37:26 hass hass[45657]: 2018-05-24 16:37:26 DEBUG (SyncWorker_0) [homeassistant.components.light.yeelight] Setting color temp: 2164 K
May 24 16:37:26 hass hass[45657]: 2018-05-24 16:37:26 ERROR (SyncWorker_0) [homeassistant.components.light.yeelight] Error when calling <function YeelightLight.set_colortemp at 0x7f7fc52c4620>: {'code': -5000, 'message': 'general error'}
```

Stimmt da was mit der Umrechnung nicht? Laut dem Hintergrund vom Slider ist in der Mitte eigentlich neutralweiß und geht nach rechts in warmweiß über?

**Comment by syssi** [comment]
Danke fuer den Feedback. Der 1. Punkt (White vs. Color) ist ein Fehler in python-yeelight. Ich werde einen Patch einreichen, so dass auch die Ceiling Light in Zukunft sauber behandelt wird.

Mein Verbesserungsvorschlag fuer individuelle Farbtemperaturen pro Model ist bisher nicht in Home Assistant aufgenommen worden. Ich rechne damit, dass das Problem im 0.72 Release geloest sein wird.

**Comment by quthla** [comment]
Du könntest ja vorerst anhand der properties gucken, ob ct, rgb None ist und dann die support flags entsprechend setzen. Letztendlich gibt yeelight auch nur anhand der properties Color oder White zurück.

**Comment by syssi** [comment]
Das stimmt. In Home Assistant gilt die Policy, dass Geräte-Logik nicht in der Home Assistant Component abgebildet werden darf/soll. Die Bibliothek darunter soll die Abstraktionsschicht liefern. Deshalb gehoert der Fix in die Bibliothek.

**Comment by quthla** [comment]
https://github.com/skorokithakis/python-yeelight/pull/8

Sollte passen, oder

**Comment by syssi** [comment]
Sauber!

**Comment by quthla** [comment]
Ist merged jetzt :D

**Comment by quthla** [comment]
Mir ist noch aufgefallen, dass die Lampe teilweise noch gut eine halbe Minute als "aus" angezeigt wird, wenn man über den set_mode Service anschaltet. Kannst du da den State intern schon auf an setzen, bis das nächste Update rein kommt?

**Comment by syssi** [comment]
Kannst du einmal das Log-Level der Komponente und Bibliothek auf Debug stellen und einen Log-Abschnitt posten, bei welchem du per `set_mode` die Lampe einschaltest? Hintergrund: Nach dem `set_mode`-Call wird normalerweise unmittelbar die Update-Methode aufgerufen, um den Zustand der Lampe zu aktualisieren. Entweder erfolgt dies nicht oder die Lampe liefert fuer eine gewisse Zeit einen falschen Zustand zurueck.

**Comment by quthla** [comment]
```
    @property
    def brightness(self) -> int:
        """Return the brightness of this light between 1..255."""
        return self._brightness
```

So wird brightness in HomeKit nicht synchronisiert.

```
    @property
    def brightness(self) -> int:
        """Return the brightness of this light between 1..255."""
        return int(self._brightness)
```

So funktioniert es. Anscheinend wird nicht automatisch zu int gecastet?

https://github.com/home-assistant/home-assistant/issues/14877

**Comment by quthla** [comment]
Arbeitest du noch an yeelight? Evtl würde ich sonst an die neue Version anpassen

**Comment by syssi** [comment]
Ich brauche noch eine Woche, dann würde ich mich kümmern. Freue mich aber über Unterstützung.
